### ISSUE TITLE
Choose a Shadow Dom Strategy

### ISSUE THREAD

**Issue by jimthedev** [AngularMN/prize-o-tron#17]
Per: http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html

**Comment by brchenderson** [comment]
I'm in for this. Anyone who knows more want to join in?

**Comment by jimthedev** [comment]
Yes! Let's chat about this.

**Comment by brchenderson** [comment]
We're recommending the EmulatedScopedShadowDomStrategy .

**Comment by jimthedev** [comment]
:+1: 

/cc @willbuck The default is to scope styles in angular. It is set that way so that outer styles can't contaminate inner scoped items.
